chore: editor forced some reformatting

diff --git a/bin/aoc b/bin/aoc
--- a/bin/aoc
+++ b/bin/aoc
@@ -1,45 +1,45 @@
 #!/usr/bin/env bash
 
-AOC_PREFIX="$( dirname $0 )"
+AOC_PREFIX="$(dirname "$0")"
 
 usage() {
-  local exitcode=${1:-1}
+    local exitcode=${1:-1}
 
-  echo "usage: aoc <command> [params]"
-  echo "       aoc -h"
-  exit $exitcode
+    echo "usage: aoc <command> [params]"
+    echo "       aoc -h"
+    exit $exitcode
 }
 
 while getopts ":h" opt; do
-  case ${opt} in
-    h ) # help
-      usage 0
-      ;;
+    case ${opt} in
+        h) # help
+            usage 0
+            ;;
 
-    \? )
-      echo "invalid option -${OPTARG}" 1>&2
-      usage
-      ;;
+        \?)
+            echo "invalid option -${OPTARG}" 1>&2
+            usage
+            ;;
 
-    : )
-      echo "option ${OPTARG} requires an argument" 1>&2
-      usage
-      ;;
-  esac
+        :)
+            echo "option ${OPTARG} requires an argument" 1>&2
+            usage
+            ;;
+    esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
 
 AOC_COMMAND=$1
 shift 1
 
 if [[ -z "${AOC_COMMAND}" ]]; then
-  usage
-else
-  SCRIPT_FILENAME="${AOC_PREFIX}/aoc-${AOC_COMMAND}"
-  if [[ ! -x "${SCRIPT_FILENAME}" ]]; then
-    echo "unknown command '${AOC_COMMAND}'"
     usage
-  fi
+else
+    SCRIPT_FILENAME="${AOC_PREFIX}/aoc-${AOC_COMMAND}"
+    if [[ ! -x "${SCRIPT_FILENAME}" ]]; then
+        echo "unknown command '${AOC_COMMAND}'"
+        usage
+    fi
 
-  ${SCRIPT_FILENAME} $@
+    ${SCRIPT_FILENAME} $@
 fi
