chore: add options and defaults to aoc-start

diff --git a/bin/aoc-start b/bin/aoc-start
--- a/bin/aoc-start
+++ b/bin/aoc-start
@@ -3,15 +3,65 @@
 ## start a container for a language
 
 usage() {
-  echo "usage: aoc-start <language> <year>"
-  exit 1
+  local exitcode=${1:-1}
+
+  langs=()
+  for filename in $( find lang -type f -name 'Dockerfile' ); do
+    langs+=("$( basename $( dirname ${filename} ) )")
+  done
+
+  echo "usage: aoc-start -l <language> [ -y <year> ] [ -t <tag> ]"
+  echo "       aoc-start [ -y <year> ] [ -t <tag> ] <language>"
+  echo ""
+  echo "Starts a Docker container for the language, with data files mounted."
+  echo ""
+  echo "Options:"
+  echo "* -l -- language"
+  echo "* -y -- year (defaults to current year)"
+  echo "* -t -- tag for language Docker image (defaults to 'latest')"
+  echo ""
+  echo "<language> must be one of: ${langs[@]}"
+
+  exit ${exitcode}
 }
+
+while getopts ":hl:t:y:" opt; do
+  case ${opt} in
+    h ) # help
+      usage 0
+      ;;
+
+    l ) # lang
+      AOC_LANG=${OPTARG}
+      ;;
+
+    t ) # tag for lang image
+      AOC_TAG=${OPTARG}
+      ;;
+
+    y ) # year
+      AOC_YEAR=${OPTARG}
+      ;;
+
+    \? )
+      echo "invalid option -${OPTARG}" 1>&2
+      usage
+      ;;
+
+    : )
+      echo "option ${OPTARG} requires an argument" 1>&2
+      usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
 
 # for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
 CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
 
-AOC_LANG=$1
-AOC_YEAR=$2
+AOC_LANG=${AOC_LANG:-$1}
+AOC_TAG=${AOC_TAG:-latest}
+AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}
 
 if [[ -z "${AOC_LANG}" ]]; then
   usage
@@ -27,13 +77,13 @@ elif [[ -z "${AOC_YEAR}" ]]; then
 elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
   echo "year out of range"
   usage
-else
-  docker run \
-    --interactive \
-    --mount type=bind,src=./years/${AOC_YEAR}/${AOC_LANG},dst=/aoc/src \
-    --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
-    --name aoc-${AOC_LANG} \
-    --rm \
-    --tty \
-    krisalyssa/aoc:${AOC_LANG}
 fi
+
+docker run \
+  --interactive \
+  --mount type=bind,src=./years/${AOC_YEAR}/${AOC_LANG},dst=/aoc/src \
+  --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
+  --name aoc-${AOC_LANG} \
+  --rm \
+  --tty \
+  ghcr.io/krisalyssa/aoc-${AOC_LANG}:${AOC_TAG}
