fix: address super-linter warnings for bash

diff --git a/bin/aoc-login b/bin/aoc-login
--- a/bin/aoc-login
+++ b/bin/aoc-login
@@ -5,34 +5,34 @@
 ##
 
 select site in GitHub Google Reddit Twitter; do
-  case "${site}" in
-  GitHub)
-    URL="https://adventofcode.com/auth/github"
-    break
-    ;;
+    case "${site}" in
+        GitHub)
+            URL="https://adventofcode.com/auth/github"
+            break
+            ;;
 
-  Google)
-    URL="https://adventofcode.com/auth/google"
-    break
-    ;;
+        Google)
+            URL="https://adventofcode.com/auth/google"
+            break
+            ;;
 
-  Reddit)
-    URL="https://adventofcode.com/auth/reddit"
-    break
-    ;;
+        Reddit)
+            URL="https://adventofcode.com/auth/reddit"
+            break
+            ;;
 
-  Twitter)
-    URL="https://adventofcode.com/auth/twitter"
-    break
-    ;;
-  esac
+        Twitter)
+            URL="https://adventofcode.com/auth/twitter"
+            break
+            ;;
+    esac
 done
 
 ## only for macOS -- need options for other OSes
 echo "Opening Safari so you can log in..."
-open -a Safari ${URL}
+open -a Safari "${URL}"
 
-cat <<EOT
+cat << EOT
 Once you have logged into your AoC account, using Safari,
 
 1. Select Develop > Show Web Inspector.
@@ -48,14 +48,14 @@ echo
 # check that the value in token is valid, as best we can (only 0-9 and a-f, 128 characters?)
 token_length=$(echo -n "${token}" | wc -c)
 if [[ "${token_length}" == "128" ]]; then
-  if echo "${token}" | grep -E -v '[^0-9a-f]' >/dev/null; then
-    echo "${token}" >./.token
-    exit 0
-  else
-    echo "pasted value contains invalid characters"
-    exit 1
-  fi
+    if echo "${token}" | grep -E -v '[^0-9a-f]' > /dev/null; then
+        echo "${token}" > ./.token
+        exit 0
+    else
+        echo "pasted value contains invalid characters"
+        exit 1
+    fi
 else
-  echo "pasted value is the wrong length (got ${token_length})"
-  exit 1
+    echo "pasted value is the wrong length (got ${token_length})"
+    exit 1
 fi
diff --git a/lang/elixir/aoc-repl b/lang/elixir/aoc-repl
--- a/lang/elixir/aoc-repl
+++ b/lang/elixir/aoc-repl
@@ -3,45 +3,45 @@
 ## start a REPL
 
 usage() {
-  local exitcode=${1:-1}
+        local exitcode=${1:-1}
 
-  echo "usage: aoc-repl [ -y <year> ] [ -t <tag> ]"
-  echo ""
-  echo "Starts a Clojure repl for a year."
-  echo ""
-  echo "Options:"
-  echo "* -y -- year (defaults to current year)"
-  echo "* -t -- tag for Docker image (defaults to 'latest')"
+        echo "usage: aoc-repl [ -y <year> ] [ -t <tag> ]"
+        echo ""
+        echo "Starts a Clojure repl for a year."
+        echo ""
+        echo "Options:"
+        echo "* -y -- year (defaults to current year)"
+        echo "* -t -- tag for Docker image (defaults to 'latest')"
 
-  exit ${exitcode}
+        exit "${exitcode}"
 }
 
 while getopts ":ht:y:" opt; do
-  case ${opt} in
-    h ) # help
-      usage 0
-      ;;
+        case ${opt} in
+        h) # help
+                usage 0
+                ;;
 
-    t ) # tag for lang image
-      AOC_TAG=${OPTARG}
-      ;;
+        t) # tag for lang image
+                AOC_TAG=${OPTARG}
+                ;;
 
-    y ) # year
-      AOC_YEAR=${OPTARG}
-      ;;
+        y) # year
+                AOC_YEAR=${OPTARG}
+                ;;
 
-    \? )
-      echo "invalid option -${OPTARG}" 1>&2
-      usage
-      ;;
+        \?)
+                echo "invalid option -${OPTARG}" 1>&2
+                usage
+                ;;
 
-    : )
-      echo "option ${OPTARG} requires an argument" 1>&2
-      usage
-      ;;
-  esac
+        :)
+                echo "option ${OPTARG} requires an argument" 1>&2
+                usage
+                ;;
+        esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
 
 # for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
 CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
@@ -50,21 +50,21 @@ AOC_TAG=${AOC_TAG:-latest}
 AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}
 
 if [[ -z "${AOC_YEAR}" ]]; then
-  usage
+        usage
 elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
-  echo "year out of range"
-  usage
+        echo "year out of range"
+        usage
 fi
 
 docker run \
-  --interactive \
-  --mount type=bind,src=./years/${AOC_YEAR}/elixir,dst=/aoc/src \
-  --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
-  --mount type=volume,src=aoc-elixir-${AOC_YEAR}-build,dst=/aoc/src/_build \
-  --mount type=volume,src=aoc-elixir-${AOC_YEAR}-deps,dst=/aoc/src/deps \
-  --mount type=volume,src=aoc-elixir-${AOC_YEAR}-mix,dst=/home/aoc/.mix \
-  --name aoc-elixir \
-  --rm \
-  --tty \
-  ghcr.io/krisalyssa/aoc/aoc-elixir:${AOC_TAG} \
-  -c "bin/repl ${AOC_DAY}"
+        --interactive \
+        --mount type=bind,src="./years/${AOC_YEAR}/elixir",dst=/aoc/src \
+        --mount type=bind,src="./years/${AOC_YEAR}/data",dst=/aoc/data \
+        --mount type=volume,src="aoc-elixir-${AOC_YEAR}-build",dst=/aoc/src/_build \
+        --mount type=volume,src="aoc-elixir-${AOC_YEAR}-deps",dst=/aoc/src/deps \
+        --mount type=volume,src="aoc-elixir-${AOC_YEAR}-mix",dst=/home/aoc/.mix \
+        --name aoc-elixir \
+        --rm \
+        --tty \
+        "ghcr.io/krisalyssa/aoc/aoc-elixir:${AOC_TAG}" \
+        -c "bin/repl ${AOC_DAY}"
diff --git a/lang/swift/aoc-run b/lang/swift/aoc-run
--- a/lang/swift/aoc-run
+++ b/lang/swift/aoc-run
@@ -3,50 +3,50 @@
 ## run a solution
 
 usage() {
-  local exitcode=${1:-1}
+        local exitcode=${1:-1}
 
-  echo "usage: aoc-run [ -y <year> ] [ -d <day> ] [ -t <tag> ]"
-  echo ""
-  echo "Runs code for a year and day."
-  echo ""
-  echo "Options:"
-  echo "* -y -- year (defaults to current year)"
-  echo "* -d -- day (defaults to current day)"
-  echo "* -t -- tag for Docker image (defaults to 'latest')"
+        echo "usage: aoc-run [ -y <year> ] [ -d <day> ] [ -t <tag> ]"
+        echo ""
+        echo "Runs code for a year and day."
+        echo ""
+        echo "Options:"
+        echo "* -y -- year (defaults to current year)"
+        echo "* -d -- day (defaults to current day)"
+        echo "* -t -- tag for Docker image (defaults to 'latest')"
 
-  exit ${exitcode}
+        exit "${exitcode}"
 }
 
 while getopts ":d:ht:y:" opt; do
-  case ${opt} in
-    d ) # day
-      AOC_DAY=${OPTARG}
-      ;;
+        case ${opt} in
+        d) # day
+                AOC_DAY=${OPTARG}
+                ;;
 
-    h ) # help
-      usage 0
-      ;;
+        h) # help
+                usage 0
+                ;;
 
-    t ) # tag for lang image
-      AOC_TAG=${OPTARG}
-      ;;
+        t) # tag for lang image
+                AOC_TAG=${OPTARG}
+                ;;
 
-    y ) # year
-      AOC_YEAR=${OPTARG}
-      ;;
+        y) # year
+                AOC_YEAR=${OPTARG}
+                ;;
 
-    \? )
-      echo "invalid option -${OPTARG}" 1>&2
-      usage
-      ;;
+        \?)
+                echo "invalid option -${OPTARG}" 1>&2
+                usage
+                ;;
 
-    : )
-      echo "option ${OPTARG} requires an argument" 1>&2
-      usage
-      ;;
-  esac
+        :)
+                echo "option ${OPTARG} requires an argument" 1>&2
+                usage
+                ;;
+        esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
 
 # for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
 CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
@@ -58,36 +58,36 @@ AOC_TAG=${AOC_TAG:-latest}
 AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}
 
 if [[ -z "${AOC_YEAR}" ]]; then
-  usage
+        usage
 elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
-  echo "year out of range"
-  usage
+        echo "year out of range"
+        usage
 elif [[ -z "${AOC_DAY}" ]]; then
-  usage
+        usage
 else
-  # strip leading zero, if any, for proper numeric comparisons
-  [[ -n "${AOC_DAY}" ]] && AOC_DAY=$((AOC_DAY + 0))
+        # strip leading zero, if any, for proper numeric comparisons
+        [[ -n "${AOC_DAY}" ]] && AOC_DAY=$((AOC_DAY + 0))
 
-  if ((AOC_DAY < 1 || AOC_DAY > 25)); then
-    echo "day out of range"
-    usage
-  elif ((AOC_YEAR == CURRENT_YEAR && AOC_DAY > CURRENT_DAY)); then
-    echo "day ${AOC_DAY} hasn't been released yet"
-    usage
-  fi
+        if ((AOC_DAY < 1 || AOC_DAY > 25)); then
+                echo "day out of range"
+                usage
+        elif ((AOC_YEAR == CURRENT_YEAR && AOC_DAY > CURRENT_DAY)); then
+                echo "day ${AOC_DAY} hasn't been released yet"
+                usage
+        fi
 
-  # now that we're done comparing numbers, force day to two digits
-  AOC_DAY=$(printf "%02d" ${AOC_DAY})
+        # now that we're done comparing numbers, force day to two digits
+        AOC_DAY=$(printf "%02d" "${AOC_DAY}")
 
-  docker run \
-    --interactive \
-    --mount type=bind,src=./years/${AOC_YEAR}/swift,dst=/aoc/src \
-    --mount type=bind,src=/Users/kcottingham/Projects/swift-aoc-common,dst=/aoc/swift-aoc-common \
-    --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
-    --mount type=volume,src=aoc-swift-${AOC_YEAR}-build,dst=/aoc/src/.build \
-    --name aoc-swift \
-    --rm \
-    --tty \
-    ghcr.io/krisalyssa/aoc/aoc-swift:${AOC_TAG} \
-    -c "bin/run ${AOC_DAY}"
+        docker run \
+                --interactive \
+                --mount type=bind,src="./years/${AOC_YEAR}/swift",dst=/aoc/src \
+                --mount type=bind,src="/Users/kcottingham/Projects/swift-aoc-common",dst=/aoc/swift-aoc-common \
+                --mount type=bind,src="./years/${AOC_YEAR}/data",dst=/aoc/data \
+                --mount type=volume,src="aoc-swift-${AOC_YEAR}-build",dst=/aoc/src/.build \
+                --name aoc-swift \
+                --rm \
+                --tty \
+                "ghcr.io/krisalyssa/aoc/aoc-swift:${AOC_TAG}" \
+                -c "bin/run ${AOC_DAY}"
 fi
diff --git a/lang/typescript/aoc-init b/lang/typescript/aoc-init
--- a/lang/typescript/aoc-init
+++ b/lang/typescript/aoc-init
@@ -1,45 +1,45 @@
 #!/bin/bash
 
 usage() {
-  local exitcode=${1:-1}
+        local exitcode=${1:-1}
 
-  echo "usage: aoc-init [ -y <year> ] [ -t <tag> ]"
-  echo ""
-  echo "Sets up a new AoC environment."
-  echo ""
-  echo "Options:"
-  echo "* -y -- year (defaults to current year)"
-  echo "* -t -- tag for Docker image (defaults to 'latest')"
+        echo "usage: aoc-init [ -y <year> ] [ -t <tag> ]"
+        echo ""
+        echo "Sets up a new AoC environment."
+        echo ""
+        echo "Options:"
+        echo "* -y -- year (defaults to current year)"
+        echo "* -t -- tag for Docker image (defaults to 'latest')"
 
-  exit ${exitcode}
+        exit "${exitcode}"
 }
 
 while getopts ":ht:y:" opt; do
-  case ${opt} in
-    h ) # help
-      usage 0
-      ;;
+        case ${opt} in
+        h) # help
+                usage 0
+                ;;
 
-    t ) # tag for lang image
-      AOC_TAG=${OPTARG}
-      ;;
+        t) # tag for lang image
+                AOC_TAG=${OPTARG}
+                ;;
 
-    y ) # year
-      AOC_YEAR=${OPTARG}
-      ;;
+        y) # year
+                AOC_YEAR=${OPTARG}
+                ;;
 
-    \? )
-      echo "invalid option -${OPTARG}" 1>&2
-      usage
-      ;;
+        \?)
+                echo "invalid option -${OPTARG}" 1>&2
+                usage
+                ;;
 
-    : )
-      echo "option ${OPTARG} requires an argument" 1>&2
-      usage
-      ;;
-  esac
+        :)
+                echo "option ${OPTARG} requires an argument" 1>&2
+                usage
+                ;;
+        esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
 
 # for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
 CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
@@ -48,36 +48,36 @@ AOC_TAG=${AOC_TAG:-latest}
 AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}
 
 if [[ -z "${AOC_YEAR}" ]]; then
-  usage
+        usage
 elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
-  echo "year out of range"
-  usage
+        echo "year out of range"
+        usage
 fi
 
 ##
 ## initalization that can take place outside the container
 ##
 
-mkdir -pv years/${AOC_YEAR}/data
-mkdir -pv years/${AOC_YEAR}/typescript
+mkdir -pv "years/${AOC_YEAR}/data"
+mkdir -pv "years/${AOC_YEAR}/typescript"
 
 if [[ -e "years/${AOC_YEAR}/typescript/package.json" ]]; then
-  echo "typescript directory already exists in years/${AOC_YEAR}"
+        echo "typescript directory already exists in years/${AOC_YEAR}"
 else
-  cp -pRv lang/typescript/skeleton/. years/${AOC_YEAR}/typescript
+        cp -pRv lang/typescript/skeleton/. "years/${AOC_YEAR}/typescript"
 
-  ##
-  ## now run initialization inside the container
-  ##
+        ##
+        ## now run initialization inside the container
+        ##
 
-  docker run \
-    --interactive \
-    --mount type=bind,src=./years/${AOC_YEAR}/typescript,dst=/aoc/src \
-    --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
-    --mount type=volume,src=aoc-typescript-${AOC_YEAR}-cache,dst=/home/aoc/.cache \
-    --name aoc-typescript \
-    --rm \
-    --tty \
-    ghcr.io/krisalyssa/aoc/aoc-typescript:${AOC_TAG} \
-    -c "bin/init ${AOC_DAY}"
+        docker run \
+                --interactive \
+                --mount type=bind,src="./years/${AOC_YEAR}/typescript",dst=/aoc/src \
+                --mount type=bind,src="./years/${AOC_YEAR}/data",dst=/aoc/data \
+                --mount type=volume,src="aoc-typescript-${AOC_YEAR}-cache",dst=/home/aoc/.cache \
+                --name aoc-typescript \
+                --rm \
+                --tty \
+                "ghcr.io/krisalyssa/aoc/aoc-typescript:${AOC_TAG}" \
+                -c "bin/init ${AOC_DAY}"
 fi
