chore: update aoc-repl and aoc-test

diff --git a/bin/aoc-test b/bin/aoc-test
--- a/bin/aoc-test
+++ b/bin/aoc-test
@@ -5,33 +5,113 @@
 ##
 
 usage() {
-  echo "usage: aoc-test <language> <year>"
-  exit 1
+  local exitcode=${1:-1}
+
+  langs=()
+  for filename in $( find lang -type f -name 'Dockerfile' | sort ); do
+    langs+=("$( basename $( dirname ${filename} ) )")
+  done
+
+  echo "usage: aoc-test -l <language> [ -y <year> ] [ -d <day> ] [ -t <tag> ]"
+  echo "       aoc-test [ -y <year> ] [ -d <day> ] [ -t <tag> ] <language>"
+  echo ""
+  echo "Runs tests for a year, day, and language."
+  echo ""
+  echo "Options:"
+  echo "* -l -- language"
+  echo "* -y -- year (defaults to current year)"
+  echo "* -d -- day (defaults to current day)"
+  echo "* -t -- tag for language Docker image (defaults to 'latest')"
+  echo ""
+  echo "<language> must be one of: ${langs[@]}"
+
+  exit ${exitcode}
 }
 
-CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
+while getopts ":d:hl:t:y:" opt; do
+  case ${opt} in
+    d ) # day
+      AOC_DAY=${OPTARG}
+      ;;
 
-AOC_LANG=$1
-AOC_YEAR=$2
+    h ) # help
+      usage 0
+      ;;
 
-shift 2
+    l ) # lang
+      AOC_LANG=${OPTARG}
+      ;;
+
+    t ) # tag for lang image
+      AOC_TAG=${OPTARG}
+      ;;
+
+    y ) # year
+      AOC_YEAR=${OPTARG}
+      ;;
+
+    \? )
+      echo "invalid option -${OPTARG}" 1>&2
+      usage
+      ;;
+
+    : )
+      echo "option ${OPTARG} requires an argument" 1>&2
+      usage
+      ;;
+  esac
+done
+shift $((OPTIND -1))
+
+# for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
+CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
+# for Linux? CURRENT_DAY=$(date --iso-8601 | cut -d '-' -f 3)
+CURRENT_DAY=$(date -I | cut -d '-' -f 3)
+
+AOC_LANG=${AOC_LANG:-$1}
+AOC_TAG=${AOC_TAG:-latest}
+AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}
+AOC_DAY=${AOC_DAY:-${CURRENT_DAY}}
 
 if [[ -z "${AOC_LANG}" ]]; then
   usage
 elif [[ ! -d "lang/${AOC_LANG}" ]]; then
   echo "unknown language ${AOC_LANG}"
   usage
-# look in years/${YEAR}/${AOC_LANG}/bin for script
-elif [[ ! -x "lang/${AOC_LANG}/test" ]]; then
-  echo "no test script for ${AOC_LANG}"
-  usage
-fi
-
-if [[ -z "${AOC_YEAR}" ]]; then
+elif [[ -x "lang/${AOC_LANG}/aoc-test" ]]; then
+  lang/${AOC_LANG}/aoc-test -y ${AOC_YEAR} -d ${AOC_DAY} -t ${AOC_TAG}
+elif [[ -z "${AOC_YEAR}" ]]; then
   usage
 elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
   echo "year out of range"
   usage
-fi
+elif [[ -z "${AOC_DAY}" ]]; then
+  usage
+else
+  # strip leading zero, if any, for proper numeric comparisons
+  [[ -n "${AOC_DAY}" ]] && AOC_DAY=$((AOC_DAY + 0))
 
-lang/${AOC_LANG}/test "${AOC_YEAR}"
+  if ((AOC_DAY < 1 || AOC_DAY > 25)); then
+    echo "day out of range"
+    usage
+  elif ((AOC_YEAR == CURRENT_YEAR && AOC_DAY > CURRENT_DAY)); then
+    echo "day ${AOC_DAY} hasn't been released yet"
+    usage
+  fi
+
+  # now that we're done comparing numbers, force day to two digits
+  AOC_DAY=$(printf "%02d" ${AOC_DAY})
+
+  ## TODO: get additional options like --mount from a config file in lang/${AOC_LANG}
+  ##       so we don't need a lang-specific script just for that
+
+  docker run \
+    --interactive \
+    --mount type=bind,src=./years/${AOC_YEAR}/${AOC_LANG},dst=/aoc/src \
+    --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
+    --name aoc-${AOC_LANG} \
+    --rm \
+    --tty \
+    ghcr.io/krisalyssa/aoc/aoc-${AOC_LANG}:${AOC_TAG} \
+    -c "bin/test ${AOC_DAY}"
+fi
