fix: address super-linter warnings for bash

diff --git a/bin/aoc-init b/bin/aoc-init
--- a/bin/aoc-init
+++ b/bin/aoc-init
@@ -5,58 +5,58 @@
 ##
 
 usage() {
-  local exitcode=${1:-1}
+    local exitcode=${1:-1}
 
-  langs=()
-  for filename in $( find lang -type f -name 'Dockerfile' | sort ); do
-    langs+=("$( basename $( dirname ${filename} ) )")
-  done
+    langs=()
+    for filename in $(find lang -type f -name 'Dockerfile' | sort); do
+        langs+=("$(basename "$(dirname "${filename}")")")
+    done
 
-  echo "usage: aoc-init -l <language> [ -y <year> ] [ -t <tag> ]"
-  echo "       aoc-init [ -y <year> ] [ -t <tag> ] <language>"
-  echo ""
-  echo "Sets up a new AoC environment."
-  echo ""
-  echo "Options:"
-  echo "* -l -- language"
-  echo "* -y -- year (defaults to current year)"
-  echo "* -t -- tag for language Docker image (defaults to 'latest')"
-  echo ""
-  echo "<language> must be one of: ${langs[@]}"
+    echo "usage: aoc-init -l <language> [ -y <year> ] [ -t <tag> ]"
+    echo "       aoc-init [ -y <year> ] [ -t <tag> ] <language>"
+    echo ""
+    echo "Sets up a new AoC environment."
+    echo ""
+    echo "Options:"
+    echo "* -l -- language"
+    echo "* -y -- year (defaults to current year)"
+    echo "* -t -- tag for language Docker image (defaults to 'latest')"
+    echo ""
+    echo "<language> must be one of: " "${langs[@]}"
 
-  exit ${exitcode}
+    exit "${exitcode}"
 }
 
 while getopts ":hl:t:y:" opt; do
-  case ${opt} in
-    h ) # help
-      usage 0
-      ;;
+    case ${opt} in
+        h) # help
+            usage 0
+            ;;
 
-    l ) # lang
-      AOC_LANG=${OPTARG}
-      ;;
+        l) # lang
+            AOC_LANG=${OPTARG}
+            ;;
 
-    t ) # tag for lang image
-      AOC_TAG=${OPTARG}
-      ;;
+        t) # tag for lang image
+            AOC_TAG=${OPTARG}
+            ;;
 
-    y ) # year
-      AOC_YEAR=${OPTARG}
-      ;;
+        y) # year
+            AOC_YEAR=${OPTARG}
+            ;;
 
-    \? )
-      echo "invalid option -${OPTARG}" 1>&2
-      usage
-      ;;
+        \?)
+            echo "invalid option -${OPTARG}" 1>&2
+            usage
+            ;;
 
-    : )
-      echo "option ${OPTARG} requires an argument" 1>&2
-      usage
-      ;;
-  esac
+        :)
+            echo "option ${OPTARG} requires an argument" 1>&2
+            usage
+            ;;
+    esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
 
 # for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
 CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
@@ -66,25 +66,25 @@ AOC_TAG=${AOC_TAG:-latest}
 AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}
 
 if [[ -z "${AOC_LANG}" ]]; then
-  usage
+    usage
 elif [[ ! -d "lang/${AOC_LANG}" ]]; then
-  echo "unknown language ${AOC_LANG}"
-  usage
+    echo "unknown language ${AOC_LANG}"
+    usage
 elif [[ -z "${AOC_YEAR}" ]]; then
-  usage
+    usage
 elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
-  echo "year out of range"
-  usage
+    echo "year out of range"
+    usage
 elif [[ ! -x "lang/${AOC_LANG}/aoc-init" ]]; then
-  echo "no init script for ${AOC_LANG}"
-  usage
+    echo "no init script for ${AOC_LANG}"
+    usage
 fi
 
 ##
 ## language-agnostic year initialization
 ##
 
-[[ ! -e years/${AOC_YEAR}/solutions.json ]] && cat << EOT > years/${AOC_YEAR}/solutions.json
+[[ ! -e "years/${AOC_YEAR}/solutions.json" ]] && cat << EOT > "years/${AOC_YEAR}/solutions.json"
 {
   "day_01": [],
   "day_02": [],
@@ -113,10 +113,10 @@ fi
   "day_25": []
 }
 EOT
-mkdir -pv years/${AOC_YEAR}/data
+mkdir -pv "years/${AOC_YEAR}/data"
 
 ##
 ## language specific initialization
 ##
 
-lang/${AOC_LANG}/aoc-init -y ${AOC_YEAR} -t ${AOC_TAG}
+"lang/${AOC_LANG}/aoc-init" -y "${AOC_YEAR}" -t "${AOC_TAG}"
