chore: add finalize job

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -2,12 +2,13 @@ name: build-images
 run-name: build docker images
 on:
   pull_request:
-    paths:
-      - lang/**
+    types:
+      - opened
+      - reopened
+      - synchronize
   push:
-    branches: [main]
-    paths:
-      - lang/**
+    branches:
+      - main
   workflow_dispatch:
     inputs:
       languages:
@@ -37,7 +38,7 @@ jobs:
           dir_names_exclude_current_dir: true
           dir_names_max_depth: 1
           matrix: true
-          path: "lang/"
+          path: 'lang/'
         #   since_last_remote_commit: true
 
       - name: log matrix
@@ -48,6 +49,7 @@ jobs:
   build:
     name: build images
     needs: [setup]
+    if: needs.setup.outputs.matrix != '[]'
     runs-on: ubuntu-latest
     concurrency:
       group: build-${{ matrix.lang }}
@@ -177,3 +179,24 @@ jobs:
         run: |
           rm -rf /tmp/.buildx-cache
           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+
+  finalize:
+    if: always()
+    # the name of this job *MUST* match the required status check *EXACTLY*, including case
+    name: finalize builds
+    runs-on: ubuntu-latest
+    needs:
+      - setup
+      - build
+    steps:
+      - name: check statuses of all build jobs
+        run: |
+          echo "${{ github.workflow }}:${{ github.job }} required job results: ${{ toJson(needs.*.result) }}"
+          passed="${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}"
+          if [[ $passed == "true" ]]; then
+            echo "success"
+            exit 0
+          else
+            echo "failed"
+            exit 1
+          fi
